/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iudigital.crudcar.presentacion;

import com.iudigital.crudcar.controller.CarController;
import com.iudigital.crudcar.dominio.Car;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Jc
 */
public class Main2 extends javax.swing.JFrame {

    private final CarController carController;
    private final String[] COLUMNS = {"ID", "MARCA", "MODELO", "AÑO", "COLOR", "TRANSMISION"};
    private final static String SELECCIONE = " -- SELECCIONE --";

    /**
     * Creates new form Main2
     */
    public Main2() {
        initComponents();
        txtCarId.setEditable(false);
        carController = new CarController();
        listCars();
        addListener();

    }

    private void listCars() {

        cbxCars.removeAllItems();
        Car car1 = new Car();
        car1.setMarca(SELECCIONE);
        car1.setModelo("");
        cbxCars.addItem(car1);
        tblCars.removeAll();
        
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);
        }

        tblCars.setModel(defaultTableModel);
        try {
            List<Car> cars = carController.obtenerCarros();
            if (cars.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount(cars.size());
            int row = 0;
            for (Car car : cars) {
                defaultTableModel.setValueAt(car.getId(), row, 0);
                defaultTableModel.setValueAt(car.getMarca(), row, 1);
                defaultTableModel.setValueAt(car.getModelo(), row, 2);
                defaultTableModel.setValueAt(car.getAnho(), row, 3);
                defaultTableModel.setValueAt(car.getColor(), row, 4);
                defaultTableModel.setValueAt(car.getTransmission(), row, 5);
                row++;

                cbxCars.addItem(car);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addListener() {
        cbxCars.addItemListener(event -> {
            Car selectedCar = (Car) event.getItem();
            if (selectedCar.getMarca().equals(SELECCIONE)) {
                txtCarId.setText("");
                txtBrandEdit.setText("");
                txtModelEdit.setText("");
                txtAnhoEdit.setText("");
                txtColorEdit.setText("");
                txtTransmissionEdit.setText("");

            } else {
                txtCarId.setText(String.valueOf(selectedCar.getId()));
                txtBrandEdit.setText(selectedCar.getMarca());
                txtModelEdit.setText(selectedCar.getModelo());
                txtAnhoEdit.setText(selectedCar.getAnho());
                txtColorEdit.setText(selectedCar.getColor());
                txtTransmissionEdit.setText(selectedCar.getTransmission());
            }
            System.out.println("selectedCar = " + selectedCar);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPanels = new javax.swing.JTabbedPane();
        jPCar = new javax.swing.JPanel();
        jPCar1 = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblAnho = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblTransmission = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtAnho = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtTransmission = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPEdit = new javax.swing.JPanel();
        lblCarros = new javax.swing.JLabel();
        cbxCars = new javax.swing.JComboBox<>();
        lblCarId = new javax.swing.JLabel();
        lblBrandEdit = new javax.swing.JLabel();
        lblModelEdit = new javax.swing.JLabel();
        lblAnhoEdit = new javax.swing.JLabel();
        lblColorEdit = new javax.swing.JLabel();
        lblTransmissionEdit = new javax.swing.JLabel();
        txtBrandEdit = new javax.swing.JTextField();
        txtModelEdit = new javax.swing.JTextField();
        txtAnhoEdit = new javax.swing.JTextField();
        txtCarId = new javax.swing.JTextField();
        txtColorEdit = new javax.swing.JTextField();
        txtTransmissionEdit = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("GESTION DE VEHICULOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPCar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los siguientes campos"));

        lblBrand.setText("MARCA");

        lblModel.setText("MODELO");

        lblAnho.setText("AÑO");

        lblColor.setText("COLOR");

        lblTransmission.setText("TRANSMISION");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCar1Layout = new javax.swing.GroupLayout(jPCar1);
        jPCar1.setLayout(jPCar1Layout);
        jPCar1Layout.setHorizontalGroup(
            jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCar1Layout.createSequentialGroup()
                .addGroup(jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCar1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblBrand)))
                .addGroup(jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCar1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCar1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblModel)))
                .addGroup(jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCar1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblAnho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPCar1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addGroup(jPCar1Layout.createSequentialGroup()
                                .addComponent(txtAnho, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)))
                .addGroup(jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        jPCar1Layout.setVerticalGroup(
            jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCar1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(lblModel)
                    .addComponent(lblAnho)
                    .addComponent(lblColor)
                    .addComponent(lblTransmission))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCars);

        javax.swing.GroupLayout jPCarLayout = new javax.swing.GroupLayout(jPCar);
        jPCar.setLayout(jPCarLayout);
        jPCarLayout.setHorizontalGroup(
            jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPCarLayout.setVerticalGroup(
            jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPCar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTPanels.addTab("Crear Carro", jPCar);

        jPEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los siguientes campos"));

        lblCarros.setText("Carros");

        cbxCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCarsActionPerformed(evt);
            }
        });

        lblCarId.setText("ID");

        lblBrandEdit.setText("MARCA");

        lblModelEdit.setText("MODELO");

        lblAnhoEdit.setText("AÑO");

        lblColorEdit.setText("COLOR");

        lblTransmissionEdit.setText("TRANSMISION");

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEditLayout = new javax.swing.GroupLayout(jPEdit);
        jPEdit.setLayout(jPEditLayout);
        jPEditLayout.setHorizontalGroup(
            jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditLayout.createSequentialGroup()
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPEditLayout.createSequentialGroup()
                        .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPEditLayout.createSequentialGroup()
                                .addComponent(txtCarId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(txtBrandEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPEditLayout.createSequentialGroup()
                                .addComponent(lblCarId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBrandEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(lblModelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(lblAnhoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lblColorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(lblTransmissionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEditLayout.createSequentialGroup()
                        .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPEditLayout.createSequentialGroup()
                                .addComponent(txtModelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(jPEditLayout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)))
                        .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar)
                            .addGroup(jPEditLayout.createSequentialGroup()
                                .addComponent(txtAnhoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtColorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtTransmissionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16))
            .addGroup(jPEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarros)
                    .addComponent(cbxCars, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPEditLayout.setVerticalGroup(
            jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCarros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarId)
                    .addComponent(lblBrandEdit)
                    .addComponent(lblModelEdit)
                    .addComponent(lblAnhoEdit)
                    .addComponent(lblColorEdit)
                    .addComponent(lblTransmissionEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrandEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnhoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransmissionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTPanels.addTab("Editar Carro", jPanel1);

        getContentPane().add(jTPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 680, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void cbxCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCarsActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtBrand.getText().trim().length() == 0) { //trim es para que no deje espacios
            JOptionPane.showMessageDialog(null, "Digite marca"); // mostramos el mensaje si el campo está vacío
            txtBrand.requestFocus(); //nos deja el cursor sobre el campo que esta vacío
            return;
        }

        if (txtModel.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe digitar Modelo");
            txtBrand.requestFocus();
            return;
        }

        if (txtAnho.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Año");
            txtBrand.requestFocus();
            return;
        }

        if (txtColor.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Color");
            txtBrand.requestFocus();
            return;
        }

        if (txtTransmission.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite tipo Transmisión");
            txtBrand.requestFocus();
            return;
        }

        Car car = new Car();
        car.setMarca(txtBrand.getText().trim());
        car.setModelo(txtModel.getText().trim());
        car.setAnho(txtAnho.getText().trim());
        car.setColor(txtColor.getText().trim());
        car.setTransmission(txtTransmission.getText().trim());

        try {
            carController.crear(car);
            txtBrand.setText("");
            txtModel.setText("");
            txtAnho.setText("");
            txtColor.setText("");
            txtTransmission.setText("");
            listCars();
            JOptionPane.showMessageDialog(null, "Carro creado con éxito");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Carro no pudo ser creado");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (txtCarId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar un carro de la Lista");
            txtCarId.requestFocus();
            return;
        }

        if (txtBrandEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite marca");
            txtBrandEdit.requestFocus();
            return;
        }

        if (txtModelEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe digitar Modelo");
            txtModelEdit.requestFocus();
            return;
        }

        if (txtAnhoEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Año");
            txtAnhoEdit.requestFocus();
            return;
        }

        if (txtColorEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Color");
            txtColorEdit.requestFocus();
            return;
        }

        if (txtTransmissionEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite tipo Transmisión");
            txtTransmissionEdit.requestFocus();
            return;
        }

        Car car = new Car();
        car.setMarca(txtBrandEdit.getText().trim());
        car.setModelo(txtModelEdit.getText().trim());
        car.setAnho(txtAnhoEdit.getText().trim());
        car.setColor(txtColorEdit.getText().trim());
        car.setTransmission(txtTransmissionEdit.getText().trim());

        int opt = JOptionPane.showConfirmDialog(null, "Desea actualizar el carro", "Confirmar salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {

            try { // en este metodo actualizar hacemos el casteo de string a integer, recibe dos parametros el id y el carro
                carController.actualizarCarro(Integer.parseInt(txtCarId.getText()), car);
                txtCarId.setText("");
                txtBrandEdit.setText("");
                txtModelEdit.setText("");
                txtAnhoEdit.setText("");
                txtColorEdit.setText("");
                txtTransmissionEdit.setText("");
                listCars();
                //mandamos el mensaje con joption pane, null porque esa opcion viene por defecto
                //busca la clase padre
                JOptionPane.showMessageDialog(null, "Se ha Actualizado el carro con éxito");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No fué posible crear el Carro");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        if (txtCarId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar un carro de la Lista");
            txtCarId.requestFocus();
            return;
        }

        int opt = JOptionPane.showConfirmDialog(null, "Está seguro de borrar carro", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {
            try {
                carController.eliminarCarro(Integer.parseInt(txtCarId.getText()));
                txtCarId.setText("");
                txtBrandEdit.setText("");
                txtModelEdit.setText("");
                txtAnhoEdit.setText("");
                txtColorEdit.setText("");
                txtTransmissionEdit.setText("");
                listCars();
                JOptionPane.showMessageDialog(null, "Se eliminó carro correctamente");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No se pudo Eliminar Carro");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Car> cbxCars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPCar;
    private javax.swing.JPanel jPCar1;
    private javax.swing.JPanel jPEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTPanels;
    private javax.swing.JLabel lblAnho;
    private javax.swing.JLabel lblAnhoEdit;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblBrandEdit;
    private javax.swing.JLabel lblCarId;
    private javax.swing.JLabel lblCarros;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorEdit;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModelEdit;
    private javax.swing.JLabel lblTransmission;
    private javax.swing.JLabel lblTransmissionEdit;
    private javax.swing.JTable tblCars;
    private javax.swing.JTextField txtAnho;
    private javax.swing.JTextField txtAnhoEdit;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtBrandEdit;
    private javax.swing.JTextField txtCarId;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtColorEdit;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModelEdit;
    private javax.swing.JTextField txtTransmission;
    private javax.swing.JTextField txtTransmissionEdit;
    // End of variables declaration//GEN-END:variables
}
